### ISSUE TITLE
Potentially missing file backend-deployment.yaml

### ISSUE THREAD

**Issue by TheSpaceCuber** [CS3219-AY2223S1/OTOT-A2-A3#1]
Referring to https://github.com/CS3219-AY2223S1/OTOT-A2-A3/blob/main/demo/a2/README.md

It states under Step 2.1:
From repo root, run `kubectl apply -f demo/manifests/k8s/backend-deployment.yaml`.

However, the file doesn't exist. Is the instruction to create our own customized manifest, paste the example manifest into a new yaml file or is there a missing file?

**Comment by moziliar** [comment]
Hi, thanks for the feedback. Yes, you have to create the file yourself. Sorry that we removed the file in the latest change without updating this line

**Comment by DrWala** [comment]
We'll update the docs tonight

**Comment by moziliar** [comment]
Updated. This is no op.
